[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "phyinc"
description = "Make sequence logos using Felsenstain's phylogenetically independent contrast metod to take evolution into account"
version="1.4"
readme = "README.md"
authors = [{name = "Lars Arvestad", email="arve@math.su.se"}]
maintainers = [{name = "Lars Arvestad", email = "arve@math.su.se"}]
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
requires-python = ">=3.10"
dependencies = [
	     "matplotlib",
	     "biopython>=1.8",
	     "logomaker",
	     "pandas",
	     "numpy",
]

[project.scripts]
phyinc = "phyinc.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = [
    "pytest",
    "build",
    "twine",
]
[project.urls]
homepage = "https://github.com/arvestad/PhyInCLogo"
